[FEATURE] 카드 드래그앤드롭으로 컬럼간(내) 이동하기
woowa-techcamp-2022/web-todo-9 pull request #34
Opened 2022-07-15 02:37 UTC by KimKwon

* Closes #31 

## ✨ 구현 기능 명세

카드의 드래그앤드롭을 컬럼 단위로만 이동 가능하게 구현했어요.
row의 위치를 변경하는 부분은 다시 시도해보려고 합니다!

## 🎁 PR Point

## 😭 어려웠던 점

자바스크립트로 좌표 추적하는 것이 난해해서 고생을 많이 했어요.
pageX, screenX, clientX 등 드래그앤드랍을 온전히 이해하고 구현하려면 좌표에 대한 이해가 수반되어야할 것 같습니다.

## ⏰ 실제 소요 시간 

5시간 + å

2022-07-16 09:34 UTC, deok2kim requested changes
끝났지만 리뷰 해봤습니다~
근데 드래그앤 드랍 쪽은 너무 낯선 부분이라 이해가 잘 안돼서 
리뷰를 못했어요 ㅠㅠ 

한 주 동안 고생 많으셨어요 😃

2022-07-16 09:34 UTC, deok2kim commented on frontend/src/components/DataProvider/index.js
> +  }
this 바인딩을 해주는 이유가 있을까요?  😃

2022-07-16 09:34 UTC, deok2kim commented on frontend/src/components/Modal/index.js
> +import { $ } from '@/commons/utils/query-selector';
```suggestion
```

중복으로 임포트된거같아요~

2022-07-16 09:34 UTC, deok2kim commented on frontend/src/components/Nav/index.js
> +import Component from '@/libs/Component';
그냥 린트때문에 순서가 바뀐건가요??ㅎㅎ

2022-07-16 09:34 UTC, deok2kim commented on frontend/src/components/TodoCard/index.scss
> +    cursor: grabbing;
디테일 좋네요 ㅎㅎ

2022-07-17 09:35 UTC, KimKwon commented on frontend/src/components/DataProvider/index.js
> +  }
인라인으로 전달하기 위해서 바인드를 사용했는데요 🤩
사실 화살표함수로 콜백을 넘겼으면 바인드느 필요 없었을 수도 있겠네요!

간단하게 비슷한 환경 코드를 작성해보았어요!

```javascript
const getSomething = () => {
  return new Promise((resolve) => {
    resolve();
  });
};

class Component {
  constructor() {
    this.state ={
      foo: 'bar',
    };
    
    // (1) 화살표 함수로 전달하는 콜백 함수
    // this.init().then(() => {
    //   console.log('arrow cb's this', this);
    //   this.doSomething();
    // });

    // (2) 일반 함수로의 전달 
    // this.init().then(function() {
    //     this.doSomething();
    //   });
    // }

    // (3) 인라인 콜백으로 전달
    // this.init().then(this.doSomething)

  async init() {
    return getSomething().then(() => {
      console.log('in getsomething callback', this);
      this.state.foo = 'poo';
    });
  }
  
  doSomething() {
    // console.log(this);
  }
	
}

const App = new Component();
```

덕기님도 이미 알고 계신 부분이겠지만!!
(1), (2), (3) 각각의 경우에 대해서 어떤 경우에 바인드가 필요한지 확인해보면 제가 bind를 사용한 이유를 좀 더 명확히 아실 수 있을 것 같아요!

2022-07-17 09:36 UTC, KimKwon commented on frontend/src/commons/utils/getOffset.js
> +export default getOffset;
이건 제가 작성하면서 조금 급하게 끼워 맞췄던 것 같아요!
조금 정확히 이해하고 정리해보겠습니다 :)

2022-07-17 09:51 UTC, KimKwon commented on frontend/src/commons/utils/getOffset.js
> +export default getOffset;
지금 보니까 실제로 사용하고 있지도 않네요.. 머쓱..

2022-07-17 13:10 UTC, deok2kim commented on frontend/src/commons/utils/getOffset.js
> +export default getOffset;
마지막에 시간이 없다보니 어쩔 수 없었나봐요 ㅎㅎ

2022-07-17 13:28 UTC, deok2kim commented on frontend/src/components/DataProvider/index.js
> +  }
1. this를 정의하는 과정이 없어서 화살표 함수를 감싸고 있는 Component 가 this
2. init() 이 this 가 되는걸까요? undefined 가 나오네요!
3. 똑같이 undefiend 가 나오네요. bind 를 사용하니 정상적으로 나옵니다.

이렇게 이해한게 맞을까요?? 🧐

2022-07-18 01:16 UTC, KimKwon commented on frontend/src/components/DataProvider/index.js
> +  }
2) init이 this가 된다기보다는 메서드가 아닌 일반 function의 경우에는 this를 undefined로 갖습니다 !

2022-07-18 01:16 UTC, merged